openapi: 3.0.0
info:
  title: Backend API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      summary: app health endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /protected:
    get:
      summary: get protected data
      description: Api is protected by the auth
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        "401":
          description: Unauthorized
  /objects:
    post:
      summary: persist object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
